name: Generate and Commit res.txt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  run-java:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - run: java Release.java

      - name: Commit and push if there are changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add all_in_one.txt
          git commit -m "update release" || exit 0
          git push
